import unittest
import unittest.mock
# Import the AnaPyzerModel class
from anapyzermodel import *
# Import the pathlib library for cross platform file path abstraction
import pathlib

class TestAnaPyzerModelMethods(unittest.TestCase):
    def setUp(self):
        # Instantiate the mock parser object to be passed to the model
        self.parserMock = unittest.mock.Mock()
        # Instantiate the mock analyzer object to be passed to the model
        self.analyzerMock = unittest.mock.Mock()
        self.model = AnaPyzerModel(self.parserMock, self.analyzerMock)
        self.log_file_mock = unittest.mock.Mock()

    # If a blank string is passed, then the model should just set the path to the default path
    def test_set_in_file_path_blank(self):
        self.model.set_in_file_path('')
        self.assertEqual(str(self.model.DEFAULT_FILE_PATH), self.model.get_in_file_path())

    # If a file path string is passed, then the model should store that file path
    def test_set_in_file_path_string(self):
        path = pathlib.Path.home()
        self.model.set_in_file_path(path)
        self.assertEqual(str(path), self.model.get_in_file_path())

    # If a blank string is passed, then the model should just set the path to the default path
    def test_set_out_file_path_blank(self):
        self.model.set_out_file_path('')
        self.assertEqual(str(self.model.DEFAULT_FILE_PATH), self.model.get_out_file_path())

    # If a file path string is passed, then the model should store that file path
    def test_set_out_file_path_string(self):
        path = pathlib.Path.home()
        self.model.set_out_file_path(path)
        self.assertEqual(str(path), self.model.get_out_file_path())

    def test_create_report_data_url_report(self):
        self.model.set_report_mode(ReportModes.URL_RPT)
        self.model._parsed_log_data = {
            0: ['2016-05-16',
                '00:00:00',
                '51.48.162.235',
                'GET',
                '/_Things/pictures/favicon-32x32.png',
                '-',
                '80',
                '-',
                '52.232.212.188',
                'Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.232.2662.102+Safari/537.36',
                'http://www.campus.edu/',
                '200',
                '0',
                '0',
                '315'],
            1: ['2016-05-16',
                '00:00:00',
                '51.48.162.235',
                'GET',
                '/_Things/revolution/stuff/videos/home/home.mp4',
                '-',
                '80',
                '-',
                '26.25.144.84',
                'Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.232.2662.102+Safari/537.36',
                'http://www.campus.edu/',
                '206',
                '0',
                '0',
                '41556'],
            '#Fields:': ['#Fields:',
                        'date',
                        'time',
                        's-ip',
                        'cs-method',
                        'cs-uri-stem',
                        'cs-uri-query',
                        's-port',
                        'cs-username',
                        'c-ip',
                        'cs(User-Agent)',
                        'cs(Referer)',
                        'sc-status',
                        'sc-substatus',
                        'sc-win32-status',
                        'time-taken'],
            'bytes-received': -1,
            'bytes-sent': -1,
            'c-ip': 8,
            'client-ip': 8,
            'cookie': -1,
            'cs(Cookie)': -1,
            'cs(Referer)': 10,
            'cs(UserAgent)': -1,
            'cs-bytes': -1,
            'cs-host': -1,
            'cs-method': 3,
            'cs-uri-query': 5,
            'cs-uri-stem': 4,
            'cs-username': 7,
            'date': 0,
            'fields': 1,
            'host': -1,
            'http-status': 11,
            'length': 2,
            'method': 3,
            'protocol-substatus': 12,
            'referer': 10,
            's-computername': -1,
            's-ip': 2,
            's-port': 6,
            's-sitename': -1,
            'sc-bytes': -1,
            'sc-status': 11,
            'sc-substatus': 12,
            'sc-win32-status': 13,
            'server-ip': 2,
            'server-name': -1,
            'server-port': 6,
            'service-name': -1,
            'time': 1,
            'time-taken': 14,
            'timestamp': 1,
            'uri-query': 5,
            'uri-stem': 4,
            'user-agent': -1,
            'username': 7,
            'win32-status': 13}
        self.model.create_report_data()
        self.analyzerMock.get_web_pages.assert_called_once_with(self.model._parsed_log_data)

    def test_create_report_data_malicious_activity_report(self):
        self.model.set_report_mode(ReportModes.SUSP_ACT)
        self.model._parsed_log_data = {
            0: ['2016-05-16',
                '00:00:00',
                '51.48.162.235',
                'GET',
                '/_Things/pictures/favicon-32x32.png',
                '-',
                '80',
                '-',
                '52.232.212.188',
                'Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.232.2662.102+Safari/537.36',
                'http://www.campus.edu/',
                '200',
                '0',
                '0',
                '315'],
            1: ['2016-05-16',
                '00:00:00',
                '51.48.162.235',
                'GET',
                '/_Things/revolution/stuff/videos/home/home.mp4',
                '-',
                '80',
                '-',
                '26.25.144.84',
                'Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.232.2662.102+Safari/537.36',
                'http://www.campus.edu/',
                '206',
                '0',
                '0',
                '41556'],
            '#Fields:': ['#Fields:',
                        'date',
                        'time',
                        's-ip',
                        'cs-method',
                        'cs-uri-stem',
                        'cs-uri-query',
                        's-port',
                        'cs-username',
                        'c-ip',
                        'cs(User-Agent)',
                        'cs(Referer)',
                        'sc-status',
                        'sc-substatus',
                        'sc-win32-status',
                        'time-taken'],
            'bytes-received': -1,
            'bytes-sent': -1,
            'c-ip': 8,
            'client-ip': 8,
            'cookie': -1,
            'cs(Cookie)': -1,
            'cs(Referer)': 10,
            'cs(UserAgent)': -1,
            'cs-bytes': -1,
            'cs-host': -1,
            'cs-method': 3,
            'cs-uri-query': 5,
            'cs-uri-stem': 4,
            'cs-username': 7,
            'date': 0,
            'fields': 1,
            'host': -1,
            'http-status': 11,
            'length': 2,
            'method': 3,
            'protocol-substatus': 12,
            'referer': 10,
            's-computername': -1,
            's-ip': 2,
            's-port': 6,
            's-sitename': -1,
            'sc-bytes': -1,
            'sc-status': 11,
            'sc-substatus': 12,
            'sc-win32-status': 13,
            'server-ip': 2,
            'server-name': -1,
            'server-port': 6,
            'service-name': -1,
            'time': 1,
            'time-taken': 14,
            'timestamp': 1,
            'uri-query': 5,
            'uri-stem': 4,
            'user-agent': -1,
            'username': 7,
            'win32-status': 13}
        self.model.create_report_data()
        self.analyzerMock.malicious_activity_report.assert_called_once_with(self.model._parsed_log_data)

    def test_create_report_data_connection_length_report(self):
        self.model.set_report_mode(ReportModes.CONN_LENGTH)
        self.model._parsed_log_data = {
            0: ['2016-05-16',
                '00:00:00',
                '51.48.162.235',
                'GET',
                '/_Things/pictures/favicon-32x32.png',
                '-',
                '80',
                '-',
                '52.232.212.188',
                'Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.232.2662.102+Safari/537.36',
                'http://www.campus.edu/',
                '200',
                '0',
                '0',
                '315'],
            1: ['2016-05-16',
                '00:00:00',
                '51.48.162.235',
                'GET',
                '/_Things/revolution/stuff/videos/home/home.mp4',
                '-',
                '80',
                '-',
                '26.25.144.84',
                'Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.232.2662.102+Safari/537.36',
                'http://www.campus.edu/',
                '206',
                '0',
                '0',
                '41556'],
            '#Fields:': ['#Fields:',
                        'date',
                        'time',
                        's-ip',
                        'cs-method',
                        'cs-uri-stem',
                        'cs-uri-query',
                        's-port',
                        'cs-username',
                        'c-ip',
                        'cs(User-Agent)',
                        'cs(Referer)',
                        'sc-status',
                        'sc-substatus',
                        'sc-win32-status',
                        'time-taken'],
            'bytes-received': -1,
            'bytes-sent': -1,
            'c-ip': 8,
            'client-ip': 8,
            'cookie': -1,
            'cs(Cookie)': -1,
            'cs(Referer)': 10,
            'cs(UserAgent)': -1,
            'cs-bytes': -1,
            'cs-host': -1,
            'cs-method': 3,
            'cs-uri-query': 5,
            'cs-uri-stem': 4,
            'cs-username': 7,
            'date': 0,
            'fields': 1,
            'host': -1,
            'http-status': 11,
            'length': 2,
            'method': 3,
            'protocol-substatus': 12,
            'referer': 10,
            's-computername': -1,
            's-ip': 2,
            's-port': 6,
            's-sitename': -1,
            'sc-bytes': -1,
            'sc-status': 11,
            'sc-substatus': 12,
            'sc-win32-status': 13,
            'server-ip': 2,
            'server-name': -1,
            'server-port': 6,
            'service-name': -1,
            'time': 1,
            'time-taken': 14,
            'timestamp': 1,
            'uri-query': 5,
            'uri-stem': 4,
            'user-agent': -1,
            'username': 7,
            'win32-status': 13}
        self.model.create_report_data()
        self.analyzerMock.get_connection_length_report.assert_called_once_with(self.model._parsed_log_data)


